add projectId to generated files
skbkontur/TypeScript.ContractGenerator pull request #54
Opened 2023-01-31 12:19 UTC by genek96

Такая возможность позволит генерировать файлы для фронта из разных проектов не мешая друг другу.
Так например, если у нас есть большое приложение на фронте, которое обращается к нескольким API, то генерировать контракты необходимо для каждого из API. Однако если они расположены в разных решениях или даже репозиториях, то генератор будет перетирать ранее сгенерированные файлы.
Добавление projectId позволит делать это без помех.

2023-01-31 14:12 UTC, fakefeik requested changes

2023-01-31 14:12 UTC, fakefeik commented on TypeScript.ContractGenerator/TypeScriptGenerator.cs
> +            this.customContentMarker = customContentMarker;
Может, в TypeScriptGenerationOptions убрать этот маркер? не хочется в этот конструктор че-то еще тащить

2023-01-31 14:12 UTC, fakefeik commented on TypeScript.ContractGenerator/Internals/FilesGenerator.cs
> +        private static string GetContentMarker(string? customContentMarker) =>
давай тут просто `=> $"// {customContentMarker ?? defaultContentMarker}";` напишем?

2023-01-31 14:12 UTC, fakefeik commented on TypeScript.ContractGenerator/Internals/FilesGenerator.cs
> +        private static void DeleteFiles(string targetDir, string searchPattern, string? customContentMarker = null)
тут не опшонал наверное, лучше всегда передавать

2023-01-31 14:12 UTC, fakefeik commented on TypeScript.ContractGenerator/Internals/FilesGenerator.cs
>              DeleteFiles(targetDir, "*.ts");
здесь не передается маркер, хотя кажется хотелось бы

2023-01-31 14:31 UTC, genek96 commented on TypeScript.ContractGenerator/Internals/FilesGenerator.cs
> +        private static void DeleteFiles(string targetDir, string searchPattern, string? customContentMarker = null)
Да, давай так

2023-01-31 14:31 UTC, genek96 commented on TypeScript.ContractGenerator/Internals/FilesGenerator.cs
> +        private static string GetContentMarker(string? customContentMarker) =>
В целом норм. Упростил

2023-01-31 14:31 UTC, genek96 commented on TypeScript.ContractGenerator/TypeScriptGenerator.cs
> +            this.customContentMarker = customContentMarker;
У самого были сомнения. В целом да, давай оставим только при вызове метода

2023-01-31 14:36 UTC, fakefeik commented on TypeScript.ContractGenerator/TypeScriptGenerator.cs
> +            this.customContentMarker = customContentMarker;
я хотел в TypeScriptGenerationOptions добавить опцию

2023-02-01 07:17 UTC, genek96 commented on TypeScript.ContractGenerator/TypeScriptGenerator.cs
> +            this.customContentMarker = customContentMarker;
А, не правильно тебя понял сначала. Соглашусь, что так будет красивее. Перенёс

2023-02-01 11:43 UTC, fakefeik commented on TypeScript.ContractGenerator/Internals/FilesGenerator.cs
> +            string? customContentMarker = null
тут бы тоже удалить опциональность, всегда передаем параметр

2023-02-01 11:44 UTC, fakefeik approved these changes

2023-02-01 11:51 UTC, merged